
apiVersion: v1
kind: Pod
metadata:
  name: tools
  namespace: default
spec:
  containers:
  - name: tools
    image: harbor.fbclouddemo.us/publicimages/ubuntu-tools-focal:0.0.3
    imagePullPolicy: Always
    command: ["/bin/bash"]
    args: ["-c", "sleep 1000000"]
    resources:
      limits:
        cpu: 100m
      requests:
        cpu: 50m
