apiVersion: v1
kind: Pod
metadata:
  name: tools
  namespace: default
spec:
  containers:
  - name: tools
    image: fabianbrash/tools:1.0
    imagePullPolicy: Always
    command: ["/bin/bash"]
    args: ["-c", "sleep 1000000"]
    resources:
      limits:
        cpu: 100m
      requests:
        cpu: 50m

